language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - cd wasabi
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - coverage run --source=directory manage.py test
after_success: coveralls
